#!/usr/bin/env bash
# Generated by scripts/run_cohort_gap_audit.py --write-run-list
# Run from repo root with thesis-data volume mounted.
set -euo pipefail
source .venv/bin/activate
export PYTHONUNBUFFERED=1

# No per-map gaps detected (or data volume offline). Batch refresh:
python scripts/run_cohort_pipeline.py --pending
python scripts/run_blocres_local_resolution.py --all
python scripts/run_qscore_validation.py --all --cohort-summary --cohort-figure


# --- Figures + thesis sync (always safe to rerun) ---
python scripts/rerun_all_figures.py
python scripts/sync_thesis_narrative_figures.py
